builds:
  - binary: mackerel-plugin-cloudflare-r2
    goos:
      - linux
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: yseto
    name: mackerel-plugin-cloudflare-r2

